name: Utils Test

on:
  pull_request:
    branches:
      - main
    paths: 'utils/**'
  push:
    branches:
      - main
    paths: 'utils/**'

jobs:
  utils-test:
    runs-on: ubuntu-latest

    env:
      STATIC_URL: https://content.portalnesia.com
      API_URL: https://api.portalnesia.com
      LINK_URL: https://link.portalnesia.com
      ACCOUNT_URL: https://accounts.portalnesia.com
      PORTAL_URL: https://portalnesia.com
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        working-directory: 'utils'